### ISSUE TITLE
In inspect page - click on commit number in the header does not work

### ISSUE THREAD

**Issue by marco-scoppetta** [graknlabs/benchmark#210]
Instead of being a link to github/commit it just appends `/inspect/commit` to the current URL

**Comment by sorsaffari** [comment]
@marco-scoppetta I understand why you have marked this as a bug, given that the current implementation doesn't produce the same behaviour in this regard.

But I also find it confusing to have the same detail on an execution card point to different paths, depending on what page the card is displayed on. 

So to bring back this behaviour while retaining consistency, I decided to make the entire ExecutionCard linked to the inspect page and the commit (as a detail on the card) always linked to the same page, i.e. the commit page on the Github repository.

Here is the PR for it: https://github.com/graknlabs/benchmark/pull/212
