### ISSUE TITLE
Use execute.sh from github

### ISSUE THREAD

**Issue by marco-scoppetta** [graknlabs/benchmark#251]
We currently upload the `execute.sh` script that is used by executor machine to run benchmark directly from service machine.

Executor should instead pull execute.sh from github so that it always uses the most updated version.

**Comment by sorsaffari** [comment]
Given that `execute.sh` is now copied over from within the `web-server` on `benchmark-service` to the executor machine, ensuring that `web-server` on `benchmark-service` is off `graknlabs/benchmark`, the motive behind the OP will be accomplished.
