### ISSUE TITLE
Server: Refactor server.ts

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/benchmark#279]
```Typescript
interface Server {
  init: (): express.Application => {};
  registerRoures: (app: express.Application) => {};
  isReady: (app: express.Application): boolean => {};
  start: (app: express.Application) => {};
}
```

**Comment by sorsaffari** [comment]
@marco-scoppetta what do you think of the above interface for managing the server?

**Comment by marco-scoppetta** [comment]
@sorsaffari it makes sense to me, the only one not very clear is `isServerReadyToStart`.
I think it should `isReady`, so that you would use it like `server.isReady()`.
Ready to start makes it sound like it's ready to be started, whereas I think we mean "is it ready to be used"? Maybe I misuderstood

**Comment by sorsaffari** [comment]
@marco-scoppetta oh that's a much a better name! I'm gonna start implementing this then.

Another question I have in mind, do you the function declarations and where we invoke those functions should be in the same and current (`server.ts`) file? or do you think it'd be better if we have `server.ts` to contain the implementation of the Server object and have the instantiation and calling of server methods within a new file (say `index.ts`) placed at `src/`?
