### ISSUE TITLE
README.md: Improve "Requirements", "Running Benchmark" and "Compiling From Source" sections

### ISSUE THREAD

**Issue by lolski** [graknlabs/benchmark#87]
Sections:
1. Python requirements
    1. Python 3.6 should be a hard requirement
    2. Installing `pipenv` should be a recommendation rather than a hard requirement. Some people may prefer to use `virtualenv` and others may just want to install the packages system-wide. Following this logic, the instruction to execute`pipenv install` should be `pip install` instead.
2. Running Benchmark
    1. Running `runner` which points to a Grakn instance started with `--benchmark`. What is the expected output if everything worked correctly. What is the output if something went wrong and how to troubleshoot it.
    2. Running `dashboard`. Interpreting the recorded data - span, child span, etc.
    3. Add starting ES and Zipkin as prerequisite to running either `runner` or `dashboard`. Be clear on what `$REPOSITORY_PATH` and `$BENCHMARK` are. Add `cd $ES_DIR` and `cd $ZIPKIN_DIR` preceding the command which runs ES and Zipkin
3. Compiling From Source:
```
bazel build //... # build all targets
bazel build //:distribution # or this, if you just want to build the zip distribution
```

**Comment by sorsaffari** [comment]
@lolski could you please reassess to see if this issue is still relevant?

**Comment by flyingsilverfin** [comment]
Closed for out of date - readme is evolving as it is.
